### ISSUE TITLE
Plugin not available in version 2022.2.2

### ISSUE THREAD

**Issue by rcastagno** [Pr1st0n/cflint-intellij#105]
I get this error message:

```Not compatible with the version of your running IDE (IntelliJ IDEA 2022.2.2)```

**Comment by Pr1st0n** [comment]
Hello @rcastagno,
Thanks for reporting. Plugin update will be available soon

**Comment by Pr1st0n** [comment]
[v0.4.0](https://github.com/Pr1st0n/cflint-intellij/releases/tag/v0.4.0) is released
