### ISSUE TITLE
Plugin incompatible with version 2021.2

### ISSUE THREAD

**Issue by bferdinandus** [Pr1st0n/cflint-intellij#33]
The plugin does not work with the newest version of IntelliJ IDEA

![image](https://user-images.githubusercontent.com/4364969/127461726-a42e50b3-cc76-483c-9a6e-9664a8a2e9a8.png)

Im using this version:
> IntelliJ IDEA 2021.2 (Ultimate Edition)
> Build #IU-212.4746.92, built on July 27, 2021

**Comment by Pr1st0n** [comment]
@bferdinandus thanks for the report!
I will resolve this issue with the next release later this week

**Comment by Pr1st0n** [comment]
Fixed in [v0.3.0](https://github.com/Pr1st0n/cflint-intellij/releases/tag/v0.3.0)
